### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by TechNoLogicRho** [sebdesign/laravel-viva-payments#14]
Hello,
thanks for the package, it is very helpfull.
I am facing a issue. When i complete the transanction in vivapayments website once i am redirect back to my laravel app i get the following error
Client error: `GET https://demo.vivapayments.com/api/orders/` resulted in a `400 Bad Request` response
Any ideas?

**Comment by sebdesign** [comment]
It seems that you are not passing the order parameter to the `Order::get()` method.
In the example it's `$request->get('orderCode')` but the documentation states otherwise:
https://developer.vivawallet.com/online-checkouts/redirect-checkout/#step-3-confirm-the-transaction

I'm not sure if that's a new change, but can you try `$request->get('s')` instead?

Otherwise can you show me the code from controller method for your success endpoint?

**Comment by TechNoLogicRho** [comment]
Dear sebdesign,
yes that was the issue. Thanks!
