### ISSUE TITLE
Fixation of issue

### ISSUE THREAD

**Issue by afrasiyabhaider** [sebdesign/laravel-viva-payments#19]
@sebdesign 
Please add **@csrf** in your readme.md file inside form otherwise it will generate **419 error** in Laravel

**Comment by sebdesign** [comment]
Thanks for the advice. The examples in the readme.md are not tested or part of the package code, so you shouldn't copy-paste them in your applications. Especially since they include sensitive payment information. They are only samples to be adjusted for your own code. If you want to submit a PR to the documentation, feel free!
